---
title: "Cleaning Data"
author: "Mark Ziemann & Kaumadi Wijesooriya"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 7
    fig_height: 7
theme: cosmo
---

## Intro

here is some background info

```{r,begin}

knitr::opts_chunk$set(fig.width=7, fig.height=7) 

```


```{r,load data}

x <- read.table("PMC_2019-analysis.tsv",header=TRUE,fill=TRUE,sep="\t")
head(x)
colnames(x)
dim(x)

```

```{r,columns1}

par(mar=c(5,12,3,1))
# omics type
omics <- x$Omics.type
omics_split <- strsplit(omics,", ")
omics <- unlist(omics_split)
res <- table(omics)
res <- res[order(res)]
res
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Omics type", xlim=c(0,600))
grid()

```

```{r,columns2}
par(mar=c(5,12,3,1))

# organism
org <- x$Organism
org_split <- strsplit(org,", ")
org <- unlist(org_split)
res <- table(org)
res <- res[order(res)]
res
barplot(tail(res,30),horiz=TRUE,las=1,cex.names = 0.5, xlab ="no. analyses",
        main = "Organism", xlim=c(0,1000))
grid()

```

```{r,columns3}
par(mar=c(5,12,3,1))
# Gene set library
GSL <-x$Gene.set.library
GSL_split <- strsplit(GSL,", ")
GSL <- unlist(GSL_split)
res<- table(GSL)
res <- res[order(res)]
res
barplot(tail(res,30),horiz=TRUE,las=1,cex.names = 0.5, xlab ="no. analyses",
        main = "Gene set library", xlim=c(0,500))
grid()

```

```{r,columns4}
par(mar=c(5,7,3,1))

# Gene set version
GSV <-x$GS.version
res <- table(GSV)
res <- res[order(res)]
res
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Gene set version", xlim=c(0,1600))
grid()

```
```{r,columns5}
par(mar=c(5,7,3,1))

# Statistical test used
ST <-x$Statistical.test.used
res <- table(ST)
res <- res[order(res)]
res
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.5, xlab="no. analyses",
        main = "Statistical test used", xlim=c(0,500))
grid()

```


```{r,columns6}
par(mar=c(5,7,3,1))

# FDR correction
FDR <-x$FDR.Correction
res <- table(FDR)
res <- res[order(res)]
res
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "FDR correction", xlim=c(0,500))
grid()

```


```{r,columns7}
par(mar=c(5,12,3,1))

# App used
App <-x$App.used
App_split <- strsplit(App,", ")
App <- unlist(App_split)
res <- table(App)
res <- res[order(res)]
res
barplot(tail(res,30),horiz=TRUE,las=1,cex.names = 0.5, xlab ="no. analyses",
        main = "App used", xlim=c(0,200))
grid()

```


## Session Information

```{r,sessioninfo}
sessionInfo()
```




