---
title: "Fetch PMC Citation Info"
author: "Mark Ziemann"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 7
    fig_height: 7
theme: cosmo
---

## Intro

Here we are going to fetch the number of citations as well as the publication date for every PMCID.

The code below fetches the number of times that A PMC has been cited.

The output format is 

1. PMCID

2. PMID

3. Number of cites

4. Pubdate

```{r,library}

library("reutils")
library("XML")
library("kableExtra")

```

Here are the functions.

```{r,functions}

get_pub_date <- function(PMCID) {
  res2 <- esummary(uid=PMCID, db = "pmc")
  res3 <- content(x=res2,as="text")
  res5 <- xmlToList(res3)
  d <- res5$DocumentSummarySet$DocumentSummary$EPubDate
  d <- gsub(" Jan ","-1-",d)
  d <- gsub(" Feb ","-2-",d)
  d <- gsub(" Mar ","-3-",d)
  d <- gsub(" Apr ","-4-",d)
  d <- gsub(" May ","-5-",d)
  d <- gsub(" Jun ","-6-",d)
  d <- gsub(" Jul ","-7-",d)
  d <- gsub(" Aug ","-8-",d)
  d <- gsub(" Sep ","-9-",d)
  d <- gsub(" Oct ","-10-",d)
  d <- gsub(" Nov ","-11-",d)
  d <- gsub(" Dec ","-12-",d)
  return(as.Date(d))
}

get_cites <- function(PMCID) {
  mylink <- elink(uid=PMCID , dbFrom="pmc", dbTo = "pubmed")
  PMID <- mylink[1]
  CITES <- elink(uid = PMID , dbFrom = "pubmed"  , linkname = "pubmed_pubmed_citedin" )
  N_CITES <- length(CITES[1])
  #PUBDATE <- get_pub_date(PMCID)
  PUBDATE <- get_pub_date(PMID)
  return(c(PMCID,PMID,N_CITES,PUBDATE))
}

# test the function
PMCID=3155154
res <- get_cites(PMCID = PMCID)
res

```

## Get cites for small group

<!-- Now to get results for a few PMC IDs to test the functions are working OK. -->

```{r,test1}

PMCIDS <- c("PMC6317205", "PMC6317219", "PMC6318854", "PMC6318897", "PMC6322516", "PMC6323737", "PMC6323741", "PMC6325784", "PMC6325795", "PMC6325889", "PMC6326702", "PMC6327033",
            "PMC6327913", "PMC6328174", "PMC6328465", "PMC6328499", "PMC6329100", "PMC6329100", "PMC6329125", "PMC6329125", "PMC6329193", "PMC6329348")

PMCIDS <- as.numeric(gsub("PMC","",PMCIDS))

res <- lapply(X = PMCIDS, FUN = get_cites)
mx <- do.call(rbind,res)
mx <- apply(X = mx, MARGIN = 2, FUN = as.numeric)
df <- as.data.frame(mx)
colnames(df) <- c("PMCID","PMID","NumCites","Pubdate")

df %>% kbl %>% kable_paper("hover", full_width = F)

plot(df$Pubdate,df$NumCites)
mylm <- lm(df$NumCites ~ df$Pubdate)

mylm

```

Looks like it works :)

## Get cites for all 

Now to get a bunch of these.

```{r,getcites}

x <- read.table("data/PMC_2019-analysis.tsv",sep="\t",header=TRUE)
head(x)
PMCIDS <- unique(x$Pubmed.Central.ID)
str(PMCIDS)

PMCIDS <- as.numeric(gsub("PMC","",PMCIDS))

res <- lapply(X = PMCIDS, FUN = get_cites)
mx <- do.call(rbind,res)
mx <- apply(X = mx, MARGIN = 2, FUN = as.numeric)
df <- as.data.frame(mx)
colnames(df) <- c("PMCID","PMID","NumCites","Pubdate")

df %>% kbl %>% kable_paper("hover", full_width = F)

plot(df$Pubdate,df$NumCites)
mylm <- lm(df$NumCites ~ df$Pubdate)

mylm

saveRDS(df,"cites_data.rds")

```

## Session information

```{r,sessioninfo}

sessionInfo()

```