---
title: "PMC Survey QC Analysis"
author: "Mark Ziemann & Kaumadi Wijesooriya"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 7
    fig_height: 5
theme: cosmo
---
  
## Intro

Here we are performing an analysis of 200 articles which is randomly selected from 1500 PMC articles. 

```{r,begin}

knitr::opts_chunk$set(fig.width=7, fig.height=5) 

library("wordcloud")
library("RColorBrewer")
library("wordcloud2")
library("reutils")
library("XML")
library("kableExtra")

```

## Overview of included and excluded analyses

```{r,exclude1}

x <- read.table("QC-analysis.tsv",header=TRUE,fill=TRUE,sep="\t")
head(x)
colnames(x)
dim(x)

exclude <- subset(x,x$GS.version=="EXCLUDE")
nrow(exclude)
length(unique(exclude$Pubmed.Central.ID))

x <- subset(x,x$GS.version!="EXCLUDE")
nrow(x)
length(unique(x$Pubmed.Central.ID))

```
## Journal 

```{r,Journal1}

journal <- x$Journal
journal_split <- strsplit(journal,", ")
journal <- unlist(journal_split)
res <- table(journal)
res <- res[order(res)]
length(res)
res

par(mar=c(1,1,1,1))
#names(res) <- gsub("Gene expression array","RNA array",names(res))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Journal", xlim=c(0,120))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Journal", xlim=c(0,1200))
grid()

```


## Omics type

```{r,omics1}

omics <- x$Omics.type
omics_split <- strsplit(omics,", ")
omics <- unlist(omics_split)
res <- table(omics)
res <- res[order(res)]
length(res)
res

par(mar=c(1,1,1,1))
names(res) <- gsub("Gene expression array","RNA array",names(res))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Omics type", xlim=c(0,600))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Omics type", xlim=c(0,600))
grid()

```

## Organism

```{r,org1}

org <- x$Organism
org_split <- strsplit(org,", ")
org <- unlist(org_split)
res <- table(org)
res <- res[order(res)]
length(res)
res

par(mar=c(1,1,1,1))
names(res) <- gsub("Homo sapiens","human",names(res))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"), scale=c(4,.5))


par(mar=c(5,12,3,1))
names(res) <- gsub("human","Homo sapiens",names(res))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Organism", xlim=c(0,1200))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Organism", xlim=c(0,1200))
grid()

```

## Gene set library

```{r,gsl1}

GSL <-x$Gene.set.library
GSL_split <- strsplit(GSL,", ")
GSL <- unlist(GSL_split)
res <- table(GSL)
res <- res[order(res)]
length(res)
which(names(res)=="Not stated")/sum(res)*100
res

par(mar=c(1,1,1,1))
names(res) <- gsub("Homo sapiens","human",names(res))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Gene set library", xlim=c(0,1000))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Gene set library", xlim=c(0,500))
grid()

```

## Gene set version

```{r,gsv1}

GSV <-x$GS.version
res <- table(GSV)
res
res[1]/sum(res)*100

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Gene set version defined", xlim=c(0,1600))
grid()

```

## Statistical test used

```{r,test1}

test <-x$Statistical.test.used
test <- strsplit(test,", ")
test <- unlist(test)
res <- table(test)
res <- res[order(res)]
res[which(names(res)=="Not stated")] / sum(res) * 100
res

par(mar=c(1,1,1,1))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Test used", xlim=c(0,1200))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "Test used", xlim=c(0,1200))
grid()

```

## FDR Correction

```{r,fdr1}

fdr <-x$FDR.Correction
fdr <- strsplit(fdr,", ")
fdr <- unlist(fdr)
res <- table(fdr)
res <- res[order(res)]
sum(res[which(names(res)!="Yes")])/sum(res)*100
res

par(mar=c(1,1,1,1))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "FDR", xlim=c(0,800))
grid()

```


## App used

```{r,app1}

App <-x$App.used
App_split <- strsplit(App,", ")
App <- unlist(App_split)
res <- table(App)
res <- res[order(res)]
res[which(names(res)=="Not stated")]/sum(res)*100
res

par(mar=c(1,1,1,1))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "App used", xlim=c(0,400))
grid()

other <- sum(res[1:(nrow(res)-10)])
res2 <- c(other,tail(res,9))
names(res2)[1] <- "Other"
par(mar=c(5,12,3,1))
barplot(res2,horiz=TRUE,las=1,cex.names = 0.7, xlab="no. analyses",
        main = "App used", xlim=c(0,500))
grid()

```

## App version

```{r,appv1}

APV <-x$App.Version
res <- table(APV)
res
res[1]/sum(res)*100

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "App version defined", xlim=c(0,1600))
grid()

```

## Code available

```{r,code1}

code <-x$Code.availability
res <- table(code)
res
res[1]/sum(res)*100

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Code availability", xlim=c(0,300))
grid()

```

## Background gene set

```{r,background1}

BG <-x$Background.gene.set
res <- table(BG)
res
sum(res[which(names(res)!="Yes")])/sum(res)*100

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Background list defined", xlim=c(0,1200))
grid()

```

## Gene lists provided

```{r,genelists1}

GL <-x$Gene.lists.provided
res <- table(GL)
res
sum(res[which(names(res)!="Yes")])/sum(res)*100

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Gene lists provided", xlim=c(0,1200))
grid()
colnames(x)

```

## Assumptions violated

```{r,assumptions1}

ok <- nrow(subset(x,Assumptions.violated=="No"))
ok
bad <- nrow(subset(x,Assumptions.violated!="No"))
bad
ok/sum(bad,ok)*100

ass <-x$Assumptions.violated
ass <- strsplit(ass,", ")
ass <- unlist(ass)
res <- table(ass)
res <- res[order(res)]
res

par(mar=c(1,1,1,1))
wordcloud(words = names(res), freq = res, min.freq = 1, 
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

par(mar=c(5,12,3,1))
barplot(tail(res,20),horiz=TRUE,las=1,cex.names = 1, xlab="no. analyses",
        main = "Assumptions violated", xlim=c(0,1400))
grid()

```

## Cross check

```{R,crosscheck}
y <- read.table("PMC_2019-analysis.tsv",header=TRUE,fill=TRUE,sep="\t")
myqc<-x[1,,drop=TRUE]
head(myqc)
mypmc<-myqc[[1]]
str(myqc)

ydat<-y[which(y$Pubmed.Central.ID==mypmc),,drop=TRUE]
str(ydat)






```

